
cron:
- description: cron_get_background_img
  url: /get_background/
  schedule: "30 1 * * *"

- description: cron_analysis_day
  url: /cron_analysis_day/
  schedule: "59 11 * * *"

- description: c
  url: /cron_analysis_hour/
  schedule: "59 * * * *"

handlers:
- url: /robots.txt
  static_path: robots.txt
  gzip: on

- url: /static/
  static_path: static
  gzip: on