# -*- coding: UTF-8 -*-
"""
Django settings for blogbwz project.

Generated by 'django-admin startproject' using Django 1.8.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

import os
import sae.const
if 'SERVER_SOFTWARE' in os.environ:

    DEBUG = True
    DOMAIN='http://xxxxxxx.applinzi.com' #你的sinaapp域名
    DB_HOST=sae.const.MYSQL_HOST

    DB_PORT=sae.const.MYSQL_PORT

    DB_USER=sae.const.MYSQL_USER

    DB_PASS=sae.const.MYSQL_PASS

    DB_DB=sae.const.MYSQL_DB
    SESSION_SERIALIZER  = 'django.contrib.sessions.serializers.PickleSerializer'
else:
    if True:
        DEBUG = True
        DOMAIN = 'http://127.0.0.1:8000'#本地测试地址
        DB_HOST='127.0.0.1'

        DB_PORT='3306'

        DB_USER='xxxx'

        DB_PASS='xxx'

        DB_DB='xxx'

        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
                'LOCATION': '127.0.0.1:11211',
                'KEY_PREFIX':'blogbwz',
            }
        }
        SESSION_ENGINE='django.contrib.sessions.backends.cache'
    else:
        from sae._restful_mysql import monkey

        monkey.patch()

        DB_HOST='w.rdc.sae.sina.com.cn'

        DB_PORT='3307'

        DB_USER='xxxxx' #新浪云Access Key

        DB_PASS='xxxxxx' #新浪云Secret Key

        DB_DB='xxxxx' #新浪云数据库名

ALLOWED_HOSTS = ['*',]
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')va^yh+3b*nh9q+-7n+2$a2(jwgqww$s6+h@0q4!1qxwtb1mj%'

# SECURITY WARNING: don't run with debug turned on in production!

SITE_ID=1

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'base',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'blogbwz.middle_blog.myMiddle',
)

ROOT_URLCONF = 'blogbwz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'debug':True,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
                'blogbwz.blog_processors.wing_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'blogbwz.wsgi.application'
AUTH_USER_MODEL = 'base.User'
# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': DB_DB,                      # Or path to database file if using sqlite3.
        'USER': DB_USER,                      # Not used with sqlite3.
        'PASSWORD': DB_PASS,                  # Not used with sqlite3.
        'HOST': DB_HOST,                      # Set to empty string for localhost. Not used with sqlite3.
        'PORT': DB_PORT,                      # Set to empty string for default. Not used with sqlite3.
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh_Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = False

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
   os.path.join(BASE_DIR,  'static'),
    #os.path.join(os.path.dirname(__file__),'static'),
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
)
STATIC_ROOT='/static/'

LOGIN_URL = '/login/'

#又拍云
MEDIA_URL = 'http://xxxx.b0.upaiyun.com/'
UPAN_BUCKETNAME = 'xxxx'
UPAN_USERNAME = 'xxxx'
UPAN_USERPASS = 'xxxx'
UPAN_IS_DEBUG = True

#邮箱
EMAIL_HOST = 'smtp.sina.com.cn'
EMAIL_PORT = '25'
EMAIL_HOST_USER = 'xxxxx@sina.com'
EMAIL_HOST_PASSWORD = 'xxxxx'
DEFAULT_FROM_EMAIL = 'xxxx博客<xxxxx@sina.com>'
SERVER_EMAIL = 'xxxx博客<xxxx@sina.com>'

#易源api，获取ip所在地，可能影响打开博客速度，请自行注释base.views.blog方法中的user_visit(request,blog)
SHOWAPI = {
    "appid":"xxxx",
    "secret":"xxxxx"
}